var namespace_k =
[
    [ "CF", "class_k_1_1_c_f.html", "class_k_1_1_c_f" ],
    [ "DB", "class_k_1_1_d_b.html", "class_k_1_1_d_b" ],
    [ "EV", "class_k_1_1_e_v.html", "class_k_1_1_e_v" ],
    [ "FN", "class_k_1_1_f_n.html", null ],
    [ "GW", "class_k_1_1_g_w.html", "class_k_1_1_g_w" ],
    [ "Gw", "class_k_1_1_gw.html", "class_k_1_1_gw" ],
    [ "Klass", "class_k_1_1_klass.html", "class_k_1_1_klass" ],
    [ "kLass", "class_k_1_1k_lass.html", "class_k_1_1k_lass" ],
    [ "MG", "class_k_1_1_m_g.html", "class_k_1_1_m_g" ],
    [ "mLevel", "struct_k_1_1m_level.html", "struct_k_1_1m_level" ],
    [ "mLevels", "struct_k_1_1m_levels.html", "struct_k_1_1m_levels" ],
    [ "mLevelsDiff", "struct_k_1_1m_levels_diff.html", "struct_k_1_1m_levels_diff" ],
    [ "mOrder", "struct_k_1_1m_order.html", "struct_k_1_1m_order" ],
    [ "mPair", "struct_k_1_1m_pair.html", "struct_k_1_1m_pair" ],
    [ "mPosition", "struct_k_1_1m_position.html", "struct_k_1_1m_position" ],
    [ "mProfit", "struct_k_1_1m_profit.html", "struct_k_1_1m_profit" ],
    [ "mQuote", "struct_k_1_1m_quote.html", "struct_k_1_1m_quote" ],
    [ "mQuoteStatus", "struct_k_1_1m_quote_status.html", "struct_k_1_1m_quote_status" ],
    [ "mQuotingParams", "struct_k_1_1m_quoting_params.html", "struct_k_1_1m_quoting_params" ],
    [ "mSafety", "struct_k_1_1m_safety.html", "struct_k_1_1m_safety" ],
    [ "mTrade", "struct_k_1_1m_trade.html", "struct_k_1_1m_trade" ],
    [ "mWallet", "struct_k_1_1m_wallet.html", "struct_k_1_1m_wallet" ],
    [ "mWallets", "struct_k_1_1m_wallets.html", "struct_k_1_1m_wallets" ],
    [ "OG", "class_k_1_1_o_g.html", "class_k_1_1_o_g" ],
    [ "PG", "class_k_1_1_p_g.html", "class_k_1_1_p_g" ],
    [ "QE", "class_k_1_1_q_e.html", "class_k_1_1_q_e" ],
    [ "QP", "class_k_1_1_q_p.html", "class_k_1_1_q_p" ],
    [ "SH", "class_k_1_1_s_h.html", "class_k_1_1_s_h" ],
    [ "UI", "class_k_1_1_u_i.html", "class_k_1_1_u_i" ]
];